services:
  postgres:
    image: postgres:13.5-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  myapp:
    image: golang
    volumes:
      - .:/go/src
