// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpaPLgtFXlFGICeRrTnOhEw7ZpJkg5t-g',
    appId: '1:1051824519847:web:c448be2ec5e56689173982',
    messagingSenderId: '1051824519847',
    projectId: 'my-data-store-cc0b4',
    authDomain: 'my-data-store-cc0b4.firebaseapp.com',
    storageBucket: 'my-data-store-cc0b4.appspot.com',
    measurementId: 'G-2PN82P85R9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxeeawlHiQm_fNH4pRwaNgHWzlCqTNRGE',
    appId: '1:1051824519847:android:e33944eb15c53d92173982',
    messagingSenderId: '1051824519847',
    projectId: 'my-data-store-cc0b4',
    storageBucket: 'my-data-store-cc0b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTo5GxWjxPcvt-ncHyTyDOiP6lQDo7tBs',
    appId: '1:1051824519847:ios:fd712169b691366b173982',
    messagingSenderId: '1051824519847',
    projectId: 'my-data-store-cc0b4',
    storageBucket: 'my-data-store-cc0b4.appspot.com',
    iosBundleId: 'com.example.petrolium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTo5GxWjxPcvt-ncHyTyDOiP6lQDo7tBs',
    appId: '1:1051824519847:ios:b4774ce388e4d336173982',
    messagingSenderId: '1051824519847',
    projectId: 'my-data-store-cc0b4',
    storageBucket: 'my-data-store-cc0b4.appspot.com',
    iosBundleId: 'com.example.petrolium.RunnerTests',
  );
}
